version: '3.8'
services:
  api:
    build: .
    image: golang:1.17
    environment:
      NODE_ENV: "development"
      ENVIRONMENT_VARIABLE: "value"
    ports:
      - "8080:8080"
    networks:
      - network-docker
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: gomad_pass
      POSTGRES_USER: gomad_default_user
      POSTGRES_DB: gomad_app
    volumes:
      - volume-docker:/var/lib/postgresql/data
    networks:
      - network-docker

volumes:
  volume-docker: {}

networks:
  network-docker: {}